# Generated by Django 4.2.11 on 2024-05-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=22)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repetitions', models.PositiveIntegerField()),
                ('muscle_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='workout.workout')),
            ],
            options={
                'ordering': ('name', 'muscle_group'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.CreateModel(
            name='FlexibilityExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stretch_type', models.CharField(max_length=50)),
                ('muscle_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='workout.workout')),
            ],
            options={
                'ordering': ('name', 'muscle_group'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnduranceTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('muscle_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='workout.workout')),
            ],
            options={
                'ordering': ('name', 'muscle_group'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('muscle_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='workout.workout')),
            ],
            options={
                'ordering': ('name', 'muscle_group'),
                'abstract': False,
            },
        ),
    ]
