# Generated by Django 4.2.11 on 2024-05-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceexercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.AddField(
            model_name='endurancetrainingexercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.AddField(
            model_name='flexibilityexercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.AddField(
            model_name='strengthtrainingexercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
    ]
