# Generated by Django 4.0 on 2024-06-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_challenge_is_shared_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_shared',
        ),
    ]
