# Generated by Django 4.0 on 2024-06-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_remove_workout_challenge_userchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='challenge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.challenge'),
        ),
    ]
