# Generated by Django 4.0 on 2024-06-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_userchallenge_workout_workout_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.challenge'),
        ),
    ]
