# Generated by Django 4.0 on 2024-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_userchallenge_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='exercise_status',
            field=models.JSONField(default=list),
        ),
    ]
